vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set({ "n", "v" }, "<leader>d", '"_d')

vim.keymap.set("n", '<Leader>ed', '<Cmd>lua MiniFiles.open()<CR>')
vim.keymap.set("n", '<Leader>ef', '<Cmd>lua MiniFiles.open(vim.api.nvim_buf_get_name(0))<CR>')
vim.keymap.set("n", '<Leader>ec', '<Cmd>edit' .. vim.fn.stdpath('config') .. '/lua/config/' .. '<CR>')
vim.keymap.set("n", '<Leader>ep', '<Cmd>edit' .. vim.fn.stdpath('config') .. '/lua/plugins/' .. '<CR>')

vim.keymap.set("n", '<Leader>f/', '<Cmd>Pick history scope="/"<CR>')
vim.keymap.set("n", '<Leader>f:', '<Cmd>Pick history scope=":"<CR>')
vim.keymap.set("n", '<Leader>fa', '<Cmd>Pick git_hunks scope="staged"<CR>')
vim.keymap.set("n", '<Leader>fA', '<Cmd>Pick git_hunks path="%" scope="staged"<CR>')
vim.keymap.set("n", '<Leader>fb', '<Cmd>Pick buffers<CR>')
vim.keymap.set("n", '<Leader>fc', '<Cmd>Pick git_commits<CR>')
vim.keymap.set("n", '<Leader>fC', '<Cmd>Pick git_commits path="%"<CR>')
vim.keymap.set("n", '<Leader>fd', '<Cmd>Pick diagnostic scope="all"<CR>')
vim.keymap.set("n", '<Leader>fD', '<Cmd>Pick diagnostic scope="current"<CR>')
vim.keymap.set("n", '<Leader>ff', '<Cmd>Pick files<CR>')
vim.keymap.set("n", '<Leader>fg', '<Cmd>Pick grep_live<CR>')
vim.keymap.set("n", '<Leader>fG', '<Cmd>Pick grep pattern="<cword>"<CR>')
vim.keymap.set("n", '<Leader>fh', '<Cmd>Pick help<CR>')
vim.keymap.set("n", '<Leader>fl', '<Cmd>Pick buf_lines scope="all"<CR>')
vim.keymap.set("n", '<Leader>fL', '<Cmd>Pick buf_lines scope="current"<CR>')
vim.keymap.set("n", '<Leader>fm', '<Cmd>Pick git_hunks<CR>')
vim.keymap.set("n", '<Leader>fM', '<Cmd>Pick git_hunks path="%"<CR>')
vim.keymap.set("n", '<Leader>fr', '<Cmd>Pick resume<CR>')
vim.keymap.set("n", '<Leader>fR', '<Cmd>Pick lsp scope="references"<CR>')
vim.keymap.set("n", '<Leader>fs', '<Cmd>Pick lsp scope="workspace_symbol"<CR>')
vim.keymap.set("n", '<Leader>fS', '<Cmd>Pick lsp scope="document_symbol"<CR>')
vim.keymap.set("n", '<Leader>fv', '<Cmd>Pick visit_paths cwd="" preserve_order=true<CR>')
vim.keymap.set("n", '<Leader>fV', '<Cmd>Pick visit_paths preserve_order=true<CR>')

local git_log_cmd = [[Git log --pretty=format:\%h\ \%as\ │\ \%s --topo-order]]
vim.keymap.set("n", '<Leader>ga', '<Cmd>Git diff --cached<CR>')
vim.keymap.set("n", '<Leader>gA', '<Cmd>Git diff --cached -- %<CR>')
vim.keymap.set("n", '<Leader>gc', '<Cmd>Git commit<CR>')
vim.keymap.set("n", '<Leader>gC', '<Cmd>Git commit --amend<CR>')
vim.keymap.set("n", '<Leader>gd', '<Cmd>Git diff<CR>')
vim.keymap.set("n", '<Leader>gD', '<Cmd>Git diff -- %<CR>')
vim.keymap.set("n", '<Leader>gl', '<Cmd>' .. git_log_cmd .. '<CR>')
vim.keymap.set("n", '<Leader>gL', '<Cmd>' .. git_log_cmd .. ' --follow -- %<CR>')
vim.keymap.set("n", '<Leader>go', '<Cmd>lua MiniDiff.toggle_overlay()<CR>')
vim.keymap.set("n", '<Leader>gs', '<Cmd>lua MiniGit.show_at_cursor()<CR>')
vim.keymap.set("x", '<Leader>gs', '<Cmd>lua MiniGit.show_at_cursor()<CR>')

vim.keymap.set("n", '<Leader>la', '<Cmd>lua vim.lsp.buf.code_action()<CR>')
vim.keymap.set("n", '<Leader>ld', '<Cmd>lua vim.diagnostic.open_float()<CR>')
vim.keymap.set('n', '<leader>lq', '<Cmd>lua vim.diagnostic.setloclist()<CR>')
vim.keymap.set("n", '<Leader>ls', '<Cmd>lua vim.lsp.buf.definition()<CR>')

vim.keymap.set("n", '<Leader>vv', '<Cmd>lua MiniVisits.add_label("active")<CR>')
vim.keymap.set("n", '<Leader>vV', '<Cmd>lua MiniVisits.remove_label("active")<CR>')
vim.keymap.set("n", '<Leader>vl', '<Cmd>lua MiniVisits.add_label()<CR>')
vim.keymap.set("n", '<Leader>vL', '<Cmd>lua MiniVisits.remove_label()<CR>')
local map_pick_active = function(keys, cwd)
  local rhs = function()
    local sort_latest = MiniVisits.gen_sort.default({ recency_weight = 1 })
    MiniExtra.pickers.visit_paths({ cwd = cwd, filter = 'active', sort = sort_latest })
  end
  vim.keymap.set("n", keys, rhs)
end
map_pick_active('<Leader>va', '')
map_pick_active('<Leader>vA', nil)
